# Generated by Django 4.1 on 2022-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0002_discorduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='discord_tag',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
