# Generated by Django 4.1 on 2022-08-26 12:39

import CinnamonSwirl.managers
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0003_discorduser_discord_tag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', CinnamonSwirl.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='recipient',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='routine',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 12, 39, 12, 346947)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 12, 39, 16, 874609)),
            preserve_default=False,
        ),
    ]
