# Generated by Django 4.1 on 2022-08-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0004_alter_discorduser_managers_reminder_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
