# Generated by Django 4.1 on 2022-08-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0005_alter_reminder_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='django_timezone',
            field=models.CharField(default='UTC', max_length=100),
            preserve_default=False,
        ),
    ]
