# Generated by Django 4.1 on 2022-08-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0006_discorduser_django_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='django_timezone',
        ),
    ]
