# Generated by Django 4.1 on 2022-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0007_remove_discorduser_django_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='timezone',
            field=models.CharField(default='US/Central', max_length=100),
        ),
    ]
