# Generated by Django 4.1 on 2022-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinnamonSwirl', '0009_reminder_end_date_reminder_routine_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='schedule',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='routine_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='routine_unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
